export const SAVE_BOOKING_REQUEST = 'SAVE_BOOKING_REQUEST';
export const FETCH_BOOKING_REQUEST = 'FETCH_BOOKING_REQUEST';
export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_BOOKING='GET_BOOKING';
export const CANCEL_BOOKING_REQUEST = 'CANCEL_BOOKING_REQUEST';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';
export const BOOKING_FAILURE = 'BOOKING_FAILURE';
