export const SAVE_TRAIN_REQUEST = 'SAVE_TRAIN_REQUEST';
export const FETCH_TRAIN_REQUEST = 'FETCH_TRAIN_REQUEST';
export const QUERY_TRAIN_REQUEST='QUERY_TRAIN_REQUEST';
export const UPDATE_TRAIN_REQUEST = 'UPDATE_TRAIN_REQUEST';
export const DELETE_TRAIN_REQUEST = 'DELETE_TRAIN_REQUEST';
export const TRAIN_SUCCESS = 'TRAIN_SUCCESS';
export const TRAIN_FAILURE = 'TRAIN_FAILURE';
